function varargout = UI_INNERKEY_export(varargin)
% UI_INNERKEY_export M-file for UI_INNERKEY_export.fig
%      UI_INNERKEY_export, by itself, creates a new UI_INNERKEY_export or raises the existing
%      singleton*.
%
%      H = UI_INNERKEY_export returns the handle to a new UI_INNERKEY_export or the handle to
%      the existing singleton*.
%
%      UI_INNERKEY_export('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in UI_INNERKEY_export.M with the given input arguments.
%
%      UI_INNERKEY_export('Property','Value',...) creates a new UI_INNERKEY_export or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before UI_INNERKEY_export_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to UI_INNERKEY_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% ======================================================================
% Copyright(c) 2019, 
% National Institute of Advanced Industrial Science and Technology
%
% Released under the MIT license 
% https://opensource.org/licenses/MIT 
% ======================================================================


% Edit the above text to modify the response to help UI_INNERKEY_export

% Last Modified by GUIDE v2.5 26-Apr-2007 20:44:32

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @UI_INNERKEY_export_OpeningFcn, ...
                   'gui_OutputFcn',  @UI_INNERKEY_export_OutputFcn, ...
                   'gui_LayoutFcn',  @UI_INNERKEY_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before UI_INNERKEY_export is made visible.
function UI_INNERKEY_export_OpeningFcn(hObject, eventdata, handles, varargin)

% Choose default command line output for UI_INNERKEY_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);
GPD=varargin{1};

if length(GPD)~=1, warndlg('GPD length is not 1. please check.');end
if ~isfield(GPD,'DataTags'), warndlg('GPD.DataTags not found. please check.');end

% str=GPD.fhdata{1}.DataTag(:);
% S=[];
% for j=1:length(str)
% 	S{end+1}=sprintf('%03d: %s',j,str{j});
% end
% set(handles.lbxG1,'String',S);
% set(handles.txtG1,'string',sprintf('total: %d',length(str)));

set(handles.lbxG1,'String',GPD.DataTags);
set(handles.txtG1,'string',sprintf('total: %d',length(GPD.DataTags)));
% get max structure depth
% dpt=0;
% for i0=1:length(GPD.fhdata)
% 	for i=1:length(GPD.fhdata{i0}.I.ResultsGroup)
% 		s=GPD.fhdata{i0}.I.ResultsGroup{i};
% 		pos=findstr(s,'.');
% 		if isempty(pos), warndlg('no structuer in results. please check.','SLA error');return;end
% 		if dpt<length(pos)+1, dpt=length(pos)+1;end
% 	end
% end
dpt=0;
for i=1:length(GPD.DataTags)
	s=GPD.DataTags{i};
	pos=findstr(s,'.');
	if isempty(pos), warndlg('no structuer in results. please check.','SLA error');return;end
	if dpt<length(pos)+1, dpt=length(pos)+1;end
end

% % make Filed name
% F=cell(1,dpt);
% Ftg=cell(1,dpt);
% for i0=1:length(GPD.fhdata)
% 	for i=1:length(GPD.fhdata{i0}.DataTag)
% 		s=GPD.fhdata{i0}.DataTag{i};
% 		pos=findstr(s,'.');
% 		if isempty(pos), warndlg('no structuer in results. please check.','SLA error');return;end
% 		pos1=[1 pos+1];
% 		pos2=[pos-1 length(s)];
% 		for j=1:length(pos1)-1
% 			num=strcmp(F{j},s(pos1(j):pos2(j)));
% 			if ~(num)
% 				F{j}{end+1}=s(pos1(j):pos2(j));
% 				Ftg{j}{end+1}=i;
% 			else
% 				Ftg{j}{num}(end+1)=i;
% 			end
% 		end
% 	end
% 	GPD.F=F;
% 	GPD.Ftg=Ftg;
% 	
% end
% make Filed name
%dpt=length(GPD.DataTags);
F=cell(1,dpt);
Ftg=cell(1,dpt);
for i=1:length(GPD.DataTags)
	s=GPD.DataTags{i};
	pos=findstr(s,'.');
	if isempty(pos), warndlg('no structuer in results. please check.','SLA error');return;end
	pos1=[1 pos+1];
	pos2=[pos-1 length(s)];
	for j=1:length(pos1)
		num=strcmp(F{j},s(pos1(j):pos2(j)));
		if ~(num)
			F{j}{end+1}=s(pos1(j):pos2(j));
			Ftg{j}{end+1}=i;
		else
			Ftg{j}{num}(end+1)=i;
		end
	end
	GPD.F=F;
	GPD.Ftg=Ftg;
end

s=[];for i=1:dpt,s{end+1}=sprintf('Field #%d',i);end
set(handles.lbxFNum,'string',s);
set(handles.lbxFName,'string',GPD.F{1});

setappdata(handles.figure1, 'GPD', GPD);

% UIWAIT makes UI_INNERKEY_export wait for user response (see UIRESUME)
 uiwait(handles.figure1);

% --- Outputs from this function are returned to the command line.
function varargout = UI_INNERKEY_export_OutputFcn(hObject, eventdata, handles) 
try
	varargout{1} = handles.output;
	uiresume(handles.figure1);
	delete(handles.figure1);
catch, 
	varargout{1}=[];
end;


% --- Executes on button press in btnTest.
function btnTest_Callback(hObject, eventdata, handles)
% hObject    handle to btnTest (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


function btnOK_Callback(hObject, eventdata, handles)
H=handles;
GPD=getappdata(H.figure1,'GPD');
H.output=GPD;
guidata(hObject, H);
uiresume(H.figure1);

function lbxFNum_Callback(hObject, eventdata, handles)
H=handles;
GPD=getappdata(H.figure1,'GPD');

set(H.lbxFName,'value',1);
set(H.lbxFName,'string',GPD(1).F{get(H.lbxFNum,'value')});


% --- Executes on selection change in lbxFiltering.
function lbxFiltering_Callback(hObject, eventdata, handles)

function rdb1_Callback(hObject, eventdata, handles)
% logic mode change

set(handles.rdbAND,'value',0);
set(handles.rdbOR,'value',0);
set(hObject,'value',1);

function btnRemove_Callback(hObject, eventdata, handles)
% Remove filtering item
H=handles;
GPD=getappdata(H.figure1,'GPD');
v=get(H.lbxFiltering,'value');
s=cellstr(get(H.lbxFiltering,'string'));

if v==0, return;end

n=ones(1,length(s));n(v)=0;
n=find(n);
if isempty(n)
	s='';
	if isfield(GPD,'Filtering'),
		GPD=rmfield(GPD,'Filtering');
	end
	%set(H.lbxFiltering,'value',1);
else
	s=s(n);
	GPD.Filtering=GPD.Filtering(n,:);
	

end

if v>length(s) && ~isempty(s)
	v=v-1;
	set(H.lbxFiltering,'value',v);
end
set(H.lbxFiltering,'string',s);
setappdata(handles.figure1, 'GPD', GPD); % save

% update
if ~isempty(n)
	% filtering execute
	FilteringExecute(handles)
end


function btnFAdd_Callback(hObject, eventdata, handles)
% Filtering ADD
H=handles;
GPD=getappdata(H.figure1,'GPD');
nF=get(H.lbxFNum,'value');
sN0=get(H.lbxFName,'string');
nN=get(H.lbxFName,'value');

if get(H.rdbAND,'value'), sLG=' -><- ';else sLG=' <--> ';end
if get(H.cbxNOT,'value'), sLG2='[NOT]';else sLG2='';end

S=get(H.lbxFiltering,'string');
if ~isfield(GPD,'Filtering'), GPD=setfield(GPD,'Filtering',[]);end
for i=nN
	sN=sN0{i};
	s=sprintf('[%s]Filed#%d: %s %s',sLG, nF, sN, sLG2);
	S{end+1}=s;
	GPD.Filtering(end+1,:)=[nF,i,strcmp(sLG,' -><- '),~isempty(sLG2)];% [Filed#,Member#,Logic(1:AND 0:OR),Logic(1:NOT)]
end
set(H.lbxFiltering,'string',S);
set(H.lbxFiltering,'value',length(S));

setappdata(handles.figure1, 'GPD', GPD); % save

% filtering execute
FilteringExecute(handles)

%=====================================================================
function FilteringExecute(handles)
H=handles;
GPD=getappdata(H.figure1,'GPD');

%selectflag=ones(1,size(GPD.fdata{1},2));
selectflag=zeros(1,length(GPD.DataTags));
num1=ones(size(selectflag));

for i=1:size(GPD.Filtering,1)
	n=GPD.Filtering(i,:);
	sF=GPD.F{n(1)}{n(2)};
	Ftg=GPD.Ftg{n(1)}{n(2)};
	
	if n(4)==1 % NOT
		filtertag=num1;
		filtertag(Ftg)=0;
	else 
		filtertag=num1*0;
		filtertag(Ftg)=1;
	end
	
	if n(3)==1 % AND
		
		selectflag=selectflag & filtertag;
	elseif n(3)==0 % OR
		selectflag=selectflag | filtertag;
	end
end
	
%set(H.lbxG2,'string',GPD.fhdata{1}.DataTag(selectflag));
set(H.lbxG2,'string',GPD.DataTags(selectflag));
set(H.txtG2,'string',sprintf('%d/%d selected.', sum(selectflag), length(selectflag)));
	
	




% --- Creates and returns a handle to the GUI figure. 
function h1 = UI_INNERKEY_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [60.003662109375;305.001953125], ...
    'taginfo', struct(...
    'figure', 2, ...
    'listbox', 4, ...
    'text', 9, ...
    'popupmenu', 4, ...
    'checkbox', 3, ...
    'edit', 2, ...
    'pushbutton', 6, ...
    'radiobutton', 3), ...
    'override', 1, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 0, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\data\PLATFORM3\P3_1_0\2ndLvlAnaPlugin\PairedTTest\UI_INNERKEY_export.m');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];

h1 = figure(...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','UI_INNERKEY',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[20.98404194812 29.67743169791],...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[623.8 299.538461538462 639 439],...
'Resize','off',...
'HandleVisibility','callback',...
'Tag','figure1',...
'UserData',[],...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxG1';

h2 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[1.16666666666667 20.0833333333333 50 13.8333333333333],...
'String',{  'リストボックス' },...
'Style','listbox',...
'Value',1,...
'Tag','lbxG1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxG2';

h3 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[54.6666666666667 20.25 50 13.6666666666667],...
'String','',...
'Style','listbox',...
'Value',1,...
'Tag','lbxG2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text1';

h4 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[1 34.75 14.5 1.08333333333333],...
'String','Group list',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text2';

h5 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[55 34.5 14.5 1.08333333333333],...
'String','Filterd list',...
'Style','text',...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnOK';

h6 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''btnOK_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[85.8333333333333 1 19.1666666666667 4.66666666666667],...
'String','OK',...
'Tag','btnOK',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxFNum';

h7 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'Callback','UI_INNERKEY_export(''lbxFNum_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[1 6 20.1666666666667 8.5],...
'String',{  'ポップアップメニュー' },...
'Style','listbox',...
'Value',1,...
'Tag','lbxFNum',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxFName';

h8 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Max',99999,...
'Position',[21.6666666666667 6 22.6666666666667 8.5],...
'String',{  'ポップアップメニュー' },...
'Style','listbox',...
'Value',1,...
'Tag','lbxFName',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'txtG1';

h9 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[1 18.8333333333333 30 1.08333333333333],...
'String',{  'スタティックテキスト' },...
'Style','text',...
'Tag','txtG1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'txtG2';

h10 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[55 18.75 30 1.08333333333333],...
'String','',...
'Style','text',...
'Tag','txtG2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'rdbAND';

h11 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''rdb1_Callback'',gcbo,[],guidata(gcbo))',...
'CData',[],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[7.66666666666667 2 12.3333333333333 1.08333333333333],...
'String','AND',...
'Style','radiobutton',...
'Tag','rdbAND',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'rdbOR';

h12 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''rdb1_Callback'',gcbo,[],guidata(gcbo))',...
'CData',[],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[7.66666666666667 3.33333333333333 12.3333333333333 1.08333333333333],...
'String','OR',...
'Style','radiobutton',...
'Value',1,...
'Tag','rdbOR',...
'UserData',[],...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxFiltering';

h13 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''lbxFiltering_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[46.3333333333333 3.41666666666667 33.6666666666667 11.1666666666667],...
'String','',...
'Style','listbox',...
'Value',1,...
'Tag','lbxFiltering',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'cbxNOT';

h14 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[7.66666666666667 0.583333333333333 9.33333333333333 1.16666666666667],...
'String','NOT',...
'Style','checkbox',...
'Tag','cbxNOT',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnFAdd';

h15 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''btnFAdd_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[21.5 1.08333333333333 21 3.25],...
'String','ADD',...
'Tag','btnFAdd',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnRemove';

h16 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_INNERKEY_export(''btnRemove_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[53.1666666666667 1.08333333333333 26.6666666666667 2],...
'String','remove',...
'Tag','btnRemove',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text6';

h17 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[1.16666666666667 15.25 14.5 1.08333333333333],...
'String','Filed position',...
'Style','text',...
'Tag','text6',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text7';

h18 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[21.6666666666667 15.0833333333333 14.5 1.08333333333333],...
'String','Filed name',...
'Style','text',...
'Tag','text7',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text8';

h19 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[46.5 14.8333333333333 14.5 1.08333333333333],...
'String','Filtering list',...
'Style','text',...
'Tag','text8',...
'CreateFcn', {@local_CreateFcn, '', appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   eval(createfcn);
end

