function initialize_axis(f)
% initialization for axis


% ======================================================================
% Copyright(c) 2019, 
% National Institute of Advanced Industrial Science and Technology
%
% Released under the MIT license 
% https://opensource.org/licenses/MIT 
% ======================================================================



axs=uimenu(f,'Label','軸の操作');
uimenu(axs,'Label','カレントのX軸を適用','Callback',['xlmd=get(gca,''XLimMode'');',...
    'ylmd=get(gca,''YLimMode'');',...
    'if ~strcmp(xlmd,''Auto'')',...
    'xlim=get(gca,''XLim'');',...
    'for ii=1:112;',...
    'tag_ch=strcat(''ch'',num2str(ii));',...
    'h=findobj(''Tag'',tag_ch);',...
    'set(h,''XLim'',xlim);',...
    'end;',...
    'end']);
uimenu(axs,'Label','カレントのY軸を適用','Callback',['xlmd=get(gca,''XLimMode'');',...
    'ylmd=get(gca,''YLimMode'');',...
    'if ~strcmp(ylmd,''Auto'')',...
    'ylim=get(gca,''YLim'');',...
    'for ii=1:112;',...
    'tag_ch=strcat(''ch'',num2str(ii));',...
    'h=findobj(''Tag'',tag_ch);',...
    'set(h,''YLim'',ylim);',...
    'end;',...
    'end']);

uimenu(axs,'Label','全ての軸をリセット','Callback',...
    ['for ii=1:112;',...
    'tag_ch=strcat(''ch'',num2str(ii));',...
    'h=findobj(''Tag'',tag_ch);',...
    'reset(h);',...
    'set(h,''Tag'',tag_ch);',...
    'end;'],'Separator','on');

%             uimenu(f,'Label','計測条件','Callback',['h=findobj(''Name'',''ETG-7000: 8x8 Mode'');',...
%               'cstr=get(h,''UserData''); msgbox(cstr,''measure conditions'');'],'Separator','on');
%-----------------------------------
