function varargout = UI_PairedTTest_export(varargin)
% UI_PAIREDTTEST_EXPORT M-file for UI_PairedTTest_export.fig
%      UI_PAIREDTTEST_EXPORT, by itself, creates a new UI_PAIREDTTEST_EXPORT or raises the existing
%      singleton*.
%
%      H = UI_PAIREDTTEST_EXPORT returns the handle to a new UI_PAIREDTTEST_EXPORT or the handle to
%      the existing singleton*.
%
%      UI_PAIREDTTEST_EXPORT('CALLBACK',hObject,eventData,handles,...) calls the local
%      function named CALLBACK in UI_PAIREDTTEST_EXPORT.M with the given input arguments.
%
%      UI_PAIREDTTEST_EXPORT('Property','Value',...) creates a new UI_PAIREDTTEST_EXPORT or raises the
%      existing singleton*.  Starting from the left, property value pairs are
%      applied to the GUI before UI_PairedTTest_export_OpeningFunction gets called.  An
%      unrecognized property name or invalid value makes property application
%      stop.  All inputs are passed to UI_PairedTTest_export_OpeningFcn via varargin.
%
%      *See GUI Options on GUIDE's Tools menu.  Choose "GUI allows only one
%      instance to run (singleton)".
%
% See also: GUIDE, GUIDATA, GUIHANDLES

% ======================================================================
% Copyright(c) 2019, 
% National Institute of Advanced Industrial Science and Technology
%
% Released under the MIT license 
% https://opensource.org/licenses/MIT 
% ======================================================================


% Edit the above text to modify the response to help UI_PairedTTest_export

% Last Modified by GUIDE v2.5 26-Apr-2007 20:44:18

% Begin initialization code - DO NOT EDIT
gui_Singleton = 1;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @UI_PairedTTest_export_OpeningFcn, ...
                   'gui_OutputFcn',  @UI_PairedTTest_export_OutputFcn, ...
                   'gui_LayoutFcn',  @UI_PairedTTest_export_LayoutFcn, ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end

if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT


% --- Executes just before UI_PairedTTest_export is made visible.
function UI_PairedTTest_export_OpeningFcn(hObject, eventdata, handles, varargin)

% Choose default command line output for UI_PairedTTest_export
handles.output = hObject;

% Update handles structure
guidata(hObject, handles);
GPD=varargin{1};
if length(GPD)~=2, 
	warndlg('Please select [ 2 groups ].');
	return;
end

GPD(1).FileNum=length(GPD(1).fdata);
GPD(2).FileNum=length(GPD(2).fdata);

% FD=fieldnames(GPD.fhdata{1}.Results.SimpleT_Test);
% for i=1:GPD.FileNum
% 	for j=1:length(FD)
% 		eval(['tmp=GPD.fhdata{i}.Results.SimpleT_Test.' FD{j} ';']);
% 		eval(['GPD.R.' FD{j} '{i}=tmp;']);
% 	end
% end

% % mean over all
% FD=fieldnames(GPD.R);
% for i=1:length(FD)
% 	tmp=eval(['GPD.R.' FD{i}]);
% 	FD2=fieldnames(eval(['GPD.R.' FD{i} '{1}']));
% 	for j=1:length(FD2)
% 		if ~iscell(eval(['GPD.R.' FD{i} '{1}.' FD2{j}]))
% 			tmp=[];
% 			for k=1:GPD.FileNum
% 				tmp(k,:)=eval(['GPD.R.' FD{i} sprintf('{%d}.',k) FD2{j}]);
% 			end
% 			eval(['GPD.mR.' FD{i} '_' FD2{j} '=mean(tmp,1);']);
% 		end
% 	end
% end
for i=1:2
	GPD(i).DataTags=[];
	GPD(i).DataPoss=[];
	%make new DataTag
	for j0=1:GPD(i).FileNum
		str=GPD(i).fhdata{j0}.DataTag(:);
		for j=1:length(str)
			GPD(i).DataTags{end+1}=sprintf('File%d.%s',j0,str{j});
			GPD(i).DataPoss{end+1}.FileNum=j0;
			GPD(i).DataPoss{end}.DataPos=GPD(i).fhdata{j0}.DataPos{j};			
		end
	end
% 	for j0=1:GPD(i).FileNum
% 		%make new DataTag
% 		
% 		str=GPD(i).fhdata{j0}.DataTag(:);
% 		for j=1:length(str)
% 			S{end+1}=sprintf('%03d: File%d.%s',j,j0,str{j});
% 			GPD(i).fhdata{j0}.DataTag{j}=sprintf('File%d.%s',j0,str{j});
% 		end
% 	end
	set(eval(sprintf('handles.lbxG%d',i)),'String',GPD(i).DataTags);
	set(eval(sprintf('handles.txtG%d',i)),'string',sprintf('total: %d',length(str)));
end


setappdata(handles.figure1, 'GPD', GPD);

% UIWAIT makes UI_PairedTTest_export wait for user response (see UIRESUME)
 uiwait(handles.figure1);



% --- Outputs from this function are returned to the command line.
function varargout = UI_PairedTTest_export_OutputFcn(hObject, eventdata, handles) 
try
	varargout{1} = handles.output;
	uiresume(handles.figure1);
	delete(handles.figure1);
catch, 
	varargout{1}=[];
end;


% --- Executes on button press in btnTest.
function btnTest_Callback(hObject, eventdata, handles)
% hObject    handle to btnTest (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)


function btnExit_Callback(hObject, eventdata, handles)

guidata(hObject, handles);
uiresume(handles.figure1);

function lbxFNum_Callback(hObject, eventdata, handles)
H=handles;
GPD=getappdata(H.figure1,'GPD');

set(H.lbxFName,'value',1);
set(H.lbxFName,'string',GPD(1).F{get(H.lbxFNum,'value')});

function btnSelect1_Callback(hObject, eventdata, handles)
% Select1
H=handles;
GPD=getappdata(H.figure1,'GPD');

GPD=UI_INNERKEY(GPD(1));




% --- Executes on selection change in lbxFiltering.
function lbxFiltering_Callback(hObject, eventdata, handles)
% hObject    handle to lbxFiltering (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hints: contents = get(hObject,'String') returns lbxFiltering contents as cell array
%        contents{get(hObject,'Value')} returns selected item from lbxFiltering

% --- Executes on button press in cbxNOT.
function cbxNOT_Callback(hObject, eventdata, handles)
% hObject    handle to cbxNOT (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)

% Hint: get(hObject,'Value') returns toggle state of cbxNOT

% --- Executes on button press in cbxNOT.
function rdb1_Callback(hObject, eventdata, handles)

set(handles.rdbAND,'value',0);
set(handles.rdbOR,'value',0);
set(hObject,'value',1);


function btnFAdd_Callback(hObject, eventdata, handles)
% Filtering ADD
H=handles;
GPD=getappdata(H.figure1,'GPD');
nF=get(H.lbxFNum,'value');
sN0=get(H.lbxFName,'string');
nN=get(H.lbxFName,'value');

if get(H.rdbAND,'value'), sLG='+';else sLG='or';end
if get(H.cbxNOT,'value'), sLG2='[NOT]';else sLG2='';end

S=get(H.lbxFiltering,'string');
%if ~isfield(GPD(1),'Filtering'), 
for i=nN
	sN=sN0{i};
	s=sprintf('[%s]Filed#%d: %s %s',sLG, nF, sN, sLG2);
	S{end+1}=s;
	GPD.Filtering{end+1}
end
set(H.lbxFiltering,'string',S);





% --- Creates and returns a handle to the GUI figure. 
function h1 = UI_PairedTTest_export_LayoutFcn(policy)
% policy - create a new figure or use a singleton. 'new' or 'reuse'.

persistent hsingleton;
if strcmpi(policy, 'reuse') & ishandle(hsingleton)
    h1 = hsingleton;
    return;
end

appdata = [];
appdata.GUIDEOptions = struct(...
    'active_h', [], ...
    'taginfo', struct(...
    'figure', 2, ...
    'listbox', 4, ...
    'text', 6, ...
    'popupmenu', 4, ...
    'checkbox', 3, ...
    'edit', 2, ...
    'pushbutton', 5, ...
    'radiobutton', 3), ...
    'override', 1, ...
    'release', 13, ...
    'resize', 'none', ...
    'accessibility', 'callback', ...
    'mfile', 1, ...
    'callbacks', 0, ...
    'singleton', 1, ...
    'syscolorfig', 1, ...
    'blocking', 0, ...
    'lastSavedFile', 'C:\data\PLATFORM3\P3_1_0\2ndLvlAnaPlugin\PairedTTest\UI_PairedTTest_export.m');
appdata.lastValidTag = 'figure1';
appdata.GUIDELayoutEditor = [];

h1 = figure(...
'Units','characters',...
'PaperUnits',get(0,'defaultfigurePaperUnits'),...
'Color',[0.831372549019608 0.815686274509804 0.784313725490196],...
'Colormap',[0 0 0.5625;0 0 0.625;0 0 0.6875;0 0 0.75;0 0 0.8125;0 0 0.875;0 0 0.9375;0 0 1;0 0.0625 1;0 0.125 1;0 0.1875 1;0 0.25 1;0 0.3125 1;0 0.375 1;0 0.4375 1;0 0.5 1;0 0.5625 1;0 0.625 1;0 0.6875 1;0 0.75 1;0 0.8125 1;0 0.875 1;0 0.9375 1;0 1 1;0.0625 1 1;0.125 1 0.9375;0.1875 1 0.875;0.25 1 0.8125;0.3125 1 0.75;0.375 1 0.6875;0.4375 1 0.625;0.5 1 0.5625;0.5625 1 0.5;0.625 1 0.4375;0.6875 1 0.375;0.75 1 0.3125;0.8125 1 0.25;0.875 1 0.1875;0.9375 1 0.125;1 1 0.0625;1 1 0;1 0.9375 0;1 0.875 0;1 0.8125 0;1 0.75 0;1 0.6875 0;1 0.625 0;1 0.5625 0;1 0.5 0;1 0.4375 0;1 0.375 0;1 0.3125 0;1 0.25 0;1 0.1875 0;1 0.125 0;1 0.0625 0;1 0 0;0.9375 0 0;0.875 0 0;0.8125 0 0;0.75 0 0;0.6875 0 0;0.625 0 0;0.5625 0 0],...
'IntegerHandle','off',...
'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
'MenuBar','none',...
'Name','UI_PairedTTest',...
'NumberTitle','off',...
'PaperPosition',get(0,'defaultfigurePaperPosition'),...
'PaperSize',[20.98404194812 29.67743169791],...
'PaperType',get(0,'defaultfigurePaperType'),...
'Position',[103.8 24.6282051282051 110.333333333333 36.8333333333333],...
'Resize','off',...
'HandleVisibility','callback',...
'Tag','figure1',...
'UserData',[],...
'Visible','on',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxG1';

h2 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[1.5 19.9166666666667 50 13.6666666666667],...
'String',{  'リストボックス' },...
'Style','listbox',...
'Value',1,...
'Tag','lbxG1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'lbxG2';

h3 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[52.3333333333333 20.0833333333333 50 13.5833333333333],...
'String',{  'リストボックス' },...
'Style','listbox',...
'Value',1,...
'Tag','lbxG2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text1';

h4 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[1.83333333333333 33.9166666666667 14.5 1.08333333333333],...
'String','Group 1',...
'Style','text',...
'Tag','text1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text2';

h5 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[52.8333333333333 34.0833333333333 14.5 1.08333333333333],...
'String','Group 2',...
'Style','text',...
'Tag','text2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'popupmenu1';

h6 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[17.3333333333333 12 20.1666666666667 1.66666666666667],...
'String',{  'ポップアップメニュー' },...
'Style','popupmenu',...
'Value',1,...
'Tag','popupmenu1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'cbxPaired';

h7 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[24 10.0833333333333 14.8333333333333 1.08333333333333],...
'String','paired',...
'Style','checkbox',...
'Tag','cbxPaired',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'text3';

h8 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','right',...
'Position',[17.6666666666667 7.66666666666667 9.16666666666667 1.25],...
'String','alpha',...
'Style','text',...
'Tag','text3',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'edtThreshold';

h9 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'BackgroundColor',[1 1 1],...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[27.3333333333333 7.58333333333333 14.1666666666667 1.58333333333333],...
'String','0.05',...
'Style','edit',...
'Tag','edtThreshold',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnTest';

h10 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_PairedTTest_export(''btnTest_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[50 9.75 11.8333333333333 1.75],...
'String','t-test',...
'Tag','btnTest',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnExit';

h11 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_PairedTTest_export(''btnExit_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[72.1666666666667 7.66666666666667 18.6666666666667 4.16666666666667],...
'String','exit',...
'Tag','btnExit',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'txtG1';

h12 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[1.66666666666667 18.4166666666667 14.5 1.08333333333333],...
'String',{  'スタティックテキスト' },...
'Style','text',...
'Tag','txtG1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'txtG2';

h13 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'HorizontalAlignment','left',...
'Position',[52.6666666666667 18.6666666666667 14.5 1.08333333333333],...
'String',{  'スタティックテキスト' },...
'Style','text',...
'Tag','txtG2',...
'CreateFcn', {@local_CreateFcn, '', appdata} );

appdata = [];
appdata.lastValidTag = 'btnSelect1';

h14 = uicontrol(...
'Parent',h1,...
'Units','characters',...
'Callback','UI_PairedTTest_export(''btnSelect1_Callback'',gcbo,[],guidata(gcbo))',...
'FontName',get(0,'defaultuicontrolFontName'),...
'FontSize',get(0,'defaultuicontrolFontSize'),...
'Position',[35.8333333333333 17.6666666666667 11.8333333333333 1.75],...
'String','Select',...
'Tag','btnSelect1',...
'CreateFcn', {@local_CreateFcn, '', appdata} );


hsingleton = h1;


% --- Set application data first then calling the CreateFcn. 
function local_CreateFcn(hObject, eventdata, createfcn, appdata)

if ~isempty(appdata)
   names = fieldnames(appdata);
   for i=1:length(names)
       name = char(names(i));
       setappdata(hObject, name, getfield(appdata,name));
   end
end

if ~isempty(createfcn)
   eval(createfcn);
end
